version: '3.5'
services:
  database:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql
  
  web:
    container_name: flask_server
    build: .
    depends_on:
      - database
    ports: 
      - 5000:5000

volumes:
  db_volume: